import { entityKind, hasOwnEntityKind, is } from "./entity.js";
import { ConsoleLogWriter, DefaultLogger, NoopLogger } from "./logger.js";
import { Column, getColumnTable } from "./column.js";
import { QueryPromise } from "./query-promise.js";
import { Subquery, WithSubquery } from "./subquery.js";
import { BaseName, ExtraConfigBuilder, ExtraConfigColumns, IsAlias, OriginalName, Table, TableColumns, TableSchema, getTableName, getTableUniqueName, isTable } from "./table.js";
import { FakePrimitiveParam, Name, Param, Placeholder, SQL, StringChunk, View, fillPlaceholders, getViewName, isDriverValueEncoder, isSQLWrapper, isView, name, noopDecoder, noopEncoder, noopMapper, param, placeholder, sql, sqlCommenter } from "./sql/sql.js";
import { ViewBaseConfig } from "./view-common.js";
import { ColumnAliasProxyHandler, ColumnTableAliasProxyHandler, RelationTableAliasProxyHandler, TableAliasProxyHandler, ViewSelectionAliasProxyHandler, aliasedColumn, aliasedRelation, aliasedTable, aliasedTableColumn, getOriginalColumnFromAlias, mapColumnsInAliasedSQLToAlias, mapColumnsInSQLToAlias } from "./alias.js";
import { ColumnBuilder, extractExtendedColumnType } from "./column-builder.js";
import { DrizzleError, DrizzleQueryError, TransactionRollbackError } from "./errors.js";
import { and, arrayContained, arrayContains, arrayOverlaps, between, bindIfParam, eq, exists, gt, gte, ilike, inArray, isNotNull, isNull, like, lt, lte, ne, not, notBetween, notExists, notIlike, notInArray, notLike, or } from "./sql/expressions/conditions.js";
import { asc, desc } from "./sql/expressions/select.js";
import { AggregatedField, Count, Many, One, Relation, RelationsBuilderColumn, RelationsBuilderJunctionColumn, RelationsBuilderTable, RelationsHelperStatic, buildRelations, buildRelationsParts, createRelationsHelper, defineRelations, defineRelationsPart, extractTablesFromSchema, fieldSelectionToSQL, getOrderByOperators, getTableAsAliasSQL, mapRelationalRow, operators, orderByOperators, processRelations, relationExtrasToSQL, relationToSQL, relationsFilterToSQL, relationsOrderToSQL } from "./relations.js";
import { avg, avgDistinct, count, countDistinct, max, min, sum, sumDistinct } from "./sql/functions/aggregate.js";
import { cosineDistance, hammingDistance, innerProduct, jaccardDistance, l1Distance, l2Distance } from "./sql/functions/vector.js";
import { CONSTANTS, applyMixins, assertUnreachable, getColumnNameAndConfig, getColumns, getTableColumns, getTableLikeName, getViewSelectedFields, haveSameKeys, isConfig, isWithEnum, mapResultRow, mapUpdateSet, orderSelectedFields, textDecoder } from "./utils.js";

export { AggregatedField, BaseName, CONSTANTS, Column, ColumnAliasProxyHandler, ColumnBuilder, ColumnTableAliasProxyHandler, ConsoleLogWriter, Count, DefaultLogger, DrizzleError, DrizzleQueryError, ExtraConfigBuilder, ExtraConfigColumns, FakePrimitiveParam, IsAlias, Many, Name, NoopLogger, One, OriginalName, Param, Placeholder, QueryPromise, Relation, RelationTableAliasProxyHandler, RelationsBuilderColumn, RelationsBuilderJunctionColumn, RelationsBuilderTable, RelationsHelperStatic, SQL, StringChunk, Subquery, Table, TableAliasProxyHandler, TableColumns, TableSchema, TransactionRollbackError, View, ViewBaseConfig, ViewSelectionAliasProxyHandler, WithSubquery, aliasedColumn, aliasedRelation, aliasedTable, aliasedTableColumn, and, applyMixins, arrayContained, arrayContains, arrayOverlaps, asc, assertUnreachable, avg, avgDistinct, between, bindIfParam, buildRelations, buildRelationsParts, cosineDistance, count, countDistinct, createRelationsHelper, defineRelations, defineRelationsPart, desc, entityKind, eq, exists, extractExtendedColumnType, extractTablesFromSchema, fieldSelectionToSQL, fillPlaceholders, getColumnNameAndConfig, getColumnTable, getColumns, getOrderByOperators, getOriginalColumnFromAlias, getTableAsAliasSQL, getTableColumns, getTableLikeName, getTableName, getTableUniqueName, getViewName, getViewSelectedFields, gt, gte, hammingDistance, hasOwnEntityKind, haveSameKeys, ilike, inArray, innerProduct, is, isConfig, isDriverValueEncoder, isNotNull, isNull, isSQLWrapper, isTable, isView, isWithEnum, jaccardDistance, l1Distance, l2Distance, like, lt, lte, mapColumnsInAliasedSQLToAlias, mapColumnsInSQLToAlias, mapRelationalRow, mapResultRow, mapUpdateSet, max, min, name, ne, noopDecoder, noopEncoder, noopMapper, not, notBetween, notExists, notIlike, notInArray, notLike, operators, or, orderByOperators, orderSelectedFields, param, placeholder, processRelations, relationExtrasToSQL, relationToSQL, relationsFilterToSQL, relationsOrderToSQL, sql, sqlCommenter, sum, sumDistinct, textDecoder };